### ISSUE TITLE
Cart Link Doesn't work on Checkout Page

### ISSUE THREAD

**Issue by osseonews** [swellstores/origin-theme#49]
Not sure, if you noticed this, but on your Origin-Theme, if you go to the checkout page, and click on the "Cart" link on the checkout page (under the Logo), the Cart link brings you to the admin panel of the store, https://STOREID.swell.store/admin/login. So every customer is redirected to the Admin login, when they click on the cart. I assume this is a bug, as a user is not supposed to be an admin.

**Comment by papertokyo** [comment]
The hosted checkout is actually a separate app to the theme, and requires setting a domain in the Swell dashboard under _Storefront > Domains_ so it knows where to link back to. However since Origin doesn't implement a `/cart` page that's going to 404. I think we can implement a handler for that though.

**Comment by ericingram** [comment]
@osseonews Can you confirm what the actual link is from the checkout? It sounds like it's going to a page that's getting redirected to /admin, which could happen if you have a storefront that's not published yet

**Comment by osseonews** [comment]
The link was /cart, but this error was happening when we were hosting Origin on Swell's servers. Once we moved Origin to our Server, and added that domain to the settings, the link didn't redirect to the admin. So it's only an issue when you use Origin hosted on Swell's servers.

Incidentally, per the other comment above, Origin doesn't impmlant a /cart page, so the clicking on that link just sends the user back to the homepage. This is sort of a bug and confusing to the user. If they click on a Cart link, they would expect to go to a cart page.

**Comment by ericingram** [comment]
@osseonews completely right. This is a bug on both points (the redirect and the lack of a /cart page on Origin). @ana-estrela is prioritizing a fix for this situation - thanks for reporting it!
