### ISSUE TITLE
Braintree Payment Doesn't Work with Swell Checkout

### ISSUE THREAD

**Issue by osseonews** [swellstores/origin-theme#50]
1. Set up Braintree Payment Method with Checkout hosted by Swell

2. Attempt to checkout. 

3. Checkout will always fail with message provided on checkout page:
`Billing method: Payment authorization failed (CVV is required.)`
Swell is not sending the CVV Code to Braintree, so Braintree rejects every payment request.

**Comment by ericingram** [comment]
@osseonews thanks for the report, we're looking into it

**Comment by osseonews** [comment]
Do you know if Swell supports Braintree yet?

**Comment by osseonews** [comment]
Is Swell still in business? This bug is still there 6 months later. We were testing Swell for a new website and still can't checkout with Braintree b/c you are not passing the CVV correctly per the original issue. Surprised nobody has bothered to fix this in over 6 months. Braintree doesn't work with  Swell.

**Comment by rodrigoddalmeida** [comment]
@osseonews this seems to be related with Swell Checkout and our Braintree integration, you can reach out to us through Support for more questions. 

I'll be closing this one since it is not related to Origin.
