### ISSUE TITLE
User account: Order date is always displayed as May 13, 2020 at orders page

### ISSUE THREAD

**Issue by SusannaKovernyk** [swellstores/origin-theme#65]
1. Open users account with completed orders.
2. Open order page
3. Take a look at the Order date field

Order date is always displayed as May 13, 2020 at orders page, the true date is not collected

![Screenshot_176](https://user-images.githubusercontent.com/79216957/108239141-42636800-7152-11eb-9553-e3ff6c1cd84c.png)

![Screenshot_178](https://user-images.githubusercontent.com/79216957/108239959-0e3c7700-7153-11eb-83b7-3a2b13dacb08.png)

**Comment by by-tim** [comment]
Fixed by [this](https://github.com/swellstores/origin-theme/commit/e0cb664e9e64784473bd8db1b66edeea2688e2c4).
