### ISSUE TITLE
Cannot read property 'format' of null

### ISSUE THREAD

**Issue by bmvega0627** [swellstores/origin-theme#68]
Added the following code to nuxt.config.js

export default{
  swell: {
    storeId: 'myIdHere',
    publicKey: 'myPublicKeyHere'
  },
......................................................................................

It produced the following error on the localhost page:

.nuxt/swell-plugin.js

  const storeId = '' || get(settings, 'store.id')
  const publicKey = '' || get(settings, 'store.public_key')

  // Bail if options aren't provided
  if (!storeId) {
    throw new Error('[swell module]: a store ID must be provided')
  }
  if (!publicKey) {
    throw new Error('[swell module]: a public API key must be provided')
  }

  ***********************************************************************

I can't get the store to appear.  I did try the following, but it rendered the store and created a different error in the terminal:

Changed the following inside nuxt.config.js

      '~/modules/swell',
      /*
       ** Initializes Swell.js SDK and injects it into Nuxt's context.
       *
       *  If you've cloned this repository from your store dashboard,
       *  these settings will already be configured in config/settings.json.
       *
       *  You can optionally override them here or using environment variables.
       *  https://github.com/swellstores/swell-theme-origin#configuration
       */
      {
        storeId: 'myStoreIdHere',
        publicKey: 'myPublicKeyHere',
        previewContent: !!process.env.SWELL_EDITOR,
        storeUrl: process.env.SWELL_STORE_URL
      }

This change rendered the store, but created the following error inside the terminal:

 ERROR  Cannot read property 'format' of null                                                                                                                                                      21:30:04

  at Object.format (node_modules/swell-js/dist/currency.js:138:28)
  at VueComponent.formatMoney (server.js:2863:44)
  at components/product-previews.js:510:41
  at Proxy.renderList (node_modules/vue/dist/vue.runtime.common.dev.js:2624:16)
  at Proxy.render (components/product-previews.js:301:11)
  at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
  at resolve (node_modules/vue-server-renderer/build.dev.js:8415:27)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by rodrigoddalmeida** [comment]
@bmvega0627 did you try to clone your store's repository? 

Currently there's some settings that are setup into that, so instead of using this project directly, you can try the custom repository we have available for your store. You should see the directions for it in your admin dashboard, then Admin>Storefront.
