### ISSUE TITLE
Purchase Quantity on Product Page

### ISSUE THREAD

**Issue by osseonews** [swellstores/origin-theme#74]
Need to add a field for purchase quantity on the Product page. Right now, the quantity defaults to 1 for every single product and the user can only increase the quantity in the cart. Customer should be able to add quantity before adding the item to the cart.

**Comment by rodrigoddalmeida** [comment]
Hey @osseonews, looks like this question might be related to Swell directly, not this theme example. You can reach out to us through Support over your dashboard.

I'll be closing this, so you can reach out over there.

**Comment by osseonews** [comment]
Actually, this is a theme issue, and nothing to do with Swell specifically. Your theme doesn't allow a user to set the purchase quantity on the product page. They can only set the purchase quantity in the cart after adding an item to the cart. For every item in the theme the QTY is preset to 1. This is not a typical UI for an ecommerce site. Users want to choose a QTY of an item before adding to the cart.
