### ISSUE TITLE
Options/Variants in Drop Down?

### ISSUE THREAD

**Issue by osseonews** [swellstores/origin-theme#75]
How do you make it so that the options/variants of a product show as a drop down select input on the product page? We have created multiple options/variants in Swell, and have selected the Option type as "Select". However, all the options show up as swatches on the product page, instead of a drop down select. 

We have compared our products to the sample products that come with the store that show up as actual drop downs for the options, and there is no difference whatseover in the settings. So why does one product with options show the options as swatches, and another as a drop down select? We must be missing something in the settings in Swell, but we can't find it.

Thanks.

**Comment by osseonews** [comment]
Found it in the code, components/ProductOptionSelect.vue (lines 163-173). The display is based on the number of options. IMHO, this is not ideal, as in many cases you want a drop down, even if you have 3 options. I'm not sure why this is set this way.

**Comment by rodrigoddalmeida** [comment]
@osseonews thanks for the suggestion - I'll be closing this since you found your way already.
