### ISSUE TITLE
New Version Does Not work: Error Cannot read property 'code' 

### ISSUE THREAD

**Issue by osseonews** [swellstores/origin-theme#77]
We installed the new version and it won't work because there is an error on start up: 
TypeError: Cannot read property 'code' of undefined.
The error is in the file: .nuxt/swell-mixin.js:24:
`this.$nuxt.$store.$swell.locale.selected().code,`

Code is not defined. For whatever reason the code is not defined. We have a currency set up in our swell admin.  If we comment out the line above in the code, and add hard code in our currency, the store works fine. 

In looking at the code in store/index.js it seems to me that the currency is saved to his.$swell.currency, not $swell.locale - so maybe that's the issue, but I'm not familiar enough with all the code. Anyway, there seems to be a bug here as commenting out the line above in swell-mixin.js gets the site working.

**Comment by rylanharper** [comment]
Any update for this?

**Comment by rodrigoddalmeida** [comment]
@osseonews @rylanharper fixed in v1.0.99, let us know if you still have issues. Thanks for the heads up!
