### ISSUE TITLE
Editor is stuck - loading forever

### ISSUE THREAD

**Issue by olegkorol** [swellstores/origin-theme#83]
Hi,

after making some minor changes to the code and pushing it to Swell the editor is stuck and keeps loading forever.

Not much was really changed: just added some dummy text in order to see if everything works as expected and if I am really able to make changes to the template.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/swellcommerce?ref_src=twsrc%5Etfw">@swellcommerce</a> is it a known issue that the editor view keeps loading forever and nothing appears?<br>Just when I thought that I found a good commerce platform... :( <a href="https://t.co/ke4vzGGJ4S">pic.twitter.com/ke4vzGGJ4S</a></p>&mdash; Oleg Korol (@oleg_korol) <a href="https://twitter.com/oleg_korol/status/1457655325742534659?ref_src=twsrc%5Etfw">November 8, 2021</a></blockquote>

Any idea what the issue could be? Is this a known bug?

**Comment by rodrigoddalmeida** [comment]
Hi @olegkorol! We'll be checking that out and follow up in our Support channel. Seems like your Editor settings got invalid for some reason, so a fix should follow really soon.

**Comment by rodrigoddalmeida** [comment]
@olegkorol following up here - it should be fixed 🙌

**Comment by olegkorol** [comment]
Thanks @rodrigoddalmeida!
Anything I can do to prevent this from happening again?
