### ISSUE TITLE
Applying filters doesn't reset page

### ISSUE THREAD

**Issue by mewa** [swellstores/origin-theme#94]
Applying a filter should take you to a screen with results, regardless of the page you're on when you apply the filter (i.e. page query string should be cleared).

Currently, if you're on a page `page_number` and apply filters that return  pages than `page_number` you will be presented with an empty page. This is because the `page` query string is not reset when applying the filters.

**Comment by logeshswell** [comment]
This issue has been fixed in Origin theme in one of the recent release and closing this issue now.
Please feel free to reopen this issue for any clarifications.
